language: android
jdk: oraclejdk8
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-google-google_play_services
    - extra-google-m2repository 
    - extra-android-m2repository
    - addon-google_apis-google-21- tools

script: ./gradlew clean build -PdisablePreDex

notifications:
  email: false
