language: android
android:
  components:
    - tools

    # The BuildTools version
    - build-tools-22.0.1

    # The SDK version
    - android-22
    # Additional components
    - extra-android-m2repository
    # emulator image
    - sys-img-armeabi-v7a-android-19

-script: ./gradlew clean build -PdisablePreDex

notifications:
  email: false
